<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WorkspaceController as W;
use App\Http\Controllers\RoadmapController as R;
Route::post('/projects/{project}/roadmaps',[R::class,'create']);
Route::patch('/roadmaps/{roadmap}',[R::class,'update']);
Route::delete('/roadmaps/{roadmap}',[R::class,'delete']);
Route::post('/roadmaps/{roadmap}/nodes',[R::class,'addNode']);
Route::patch('/roadmaps/{roadmap}/nodes/{node}',[R::class,'moveNode']);
Route::delete('/roadmaps/{roadmap}/nodes/{node}',[R::class,'deleteNode']);
Route::post('/roadmaps/{roadmap}/edges',[R::class,'addEdge']);
Route::delete('/roadmaps/{roadmap}/edges/{edge}',[R::class,'deleteEdge']);
Route::get('/workspace',[W::class,'index']);
Route::post('/projects',[W::class,'createProject']);
Route::post('/projects/{project}/roadmap/reorder',[W::class,'reorderRoadmap']);
Route::patch('/projects/{project}',[W::class,'updateProject']);
Route::delete('/projects/{project}',[W::class,'deleteProject']);
Route::post('/tasks',[W::class,'createTask']);
Route::post('/tasks/reorder',[W::class,'reorderTasks']);
Route::patch('/tasks/{task}',[W::class,'updateTask']);
Route::delete('/tasks/{task}',[W::class,'deleteTask']);
Route::post('/tasks/{task}/activities',[W::class,'createActivity']);
Route::post('/tasks/{task}/activities/reorder',[W::class,'reorderActivities']);
Route::patch('/activities/{activity}',[W::class,'updateActivity']);
Route::delete('/activities/{activity}',[W::class,'deleteActivity']);
Route::post('/activities/{activity}/comments',[W::class,'createComment']);
Route::patch('/comments/{comment}',[W::class,'updateComment']);
Route::delete('/comments/{comment}',[W::class,'deleteComment']);
Route::post('/images',[W::class,'uploadImage']);
